import "./globals.css";
import Header from "@/app/Header";
import Footer from "./Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-soft-orange"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
